"""empty message

Revision ID: d8e0f80631fb
Revises: bb5da1e68550
Create Date: 2022-10-11 14:46:28.100282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8e0f80631fb"
down_revision = "bb5da1e68550"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint("email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
